name: Build Action

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  call-basic-validation: # The reusable workflow can be found here: https://github.com/actions/reusable-workflows/blob/main/.github/workflows/basic-validation.yml
    name: Basic validation
    #uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main
    uses: IvanZosimov/reusable-workflows/.github/workflows/basic-validation.yml@main